FROM busybox:latest

# for mysql
Volume /var/lib/mysql

# for redis
Volume /data

# for assets
Volume /app/webpack/node_modules

# for app
Volume /app/rails/vendor/bundle
Volume /app/rails/.bundle

# assets & rails
Volume /app/rails/public/assets
